let animales = ["Perro", "Gato", "Periquito", "Conejo"];
console.log("Número de elementos: ",animales.length);
console.log(animales);
animales.push("Hamster");
console.log("Número de elementos: ",animales.length);
console.log(animales);
let eliminado = animales.pop();
console.log("Elemento eliminado: ",eliminado);
console.log("Número de elementos: ",animales.length);
console.log(animales);