let valortrue = true;
let valorfalse = false;
console.log("Valor true:", valortrue);
console.log("Valor false:", valorfalse);
console.log("Valor true a string:", valortrue.toString());
console.log("Valor false a string:", valorfalse.toString());
valortrue = new Boolean(true);
valorfalse = new Boolean(false);
console.log("Tipo dato boolean con valor true:", valortrue);
console.log("Tipo dato boolean con valor false:", valorfalse);
console.log("Tipo dato boolean con valor true a string:", valortrue.toString());
console.log("Tipo dato boolean con valor false a string:", valorfalse.toString());